kafkaConfig:
  brokers:
  -  'localhost:36715'

esConfig:
  url: "http://localhost:35355"
  username: "elastic"
  password: "password"

manager:
  url: 'https://plugin_template_url' 
  config_topic: 'config_topic'



  